Revert "avoid the try-except block for validating package in the cache"
This reverts commit cd985c52fdff36db3d5abdaa877398614dd228cb.

You can't just assume the source name will be in the cache.

Here's an example:

>>> f = c['cinnamon-l10n']
>>> f.candidate.source_name
'cinnamon-translations'
>>> c['cinnamon-translations']
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apt/cache.py", line 285, in __getitem__
    return self._weakref[key]
  File "/usr/lib/python3.6/weakref.py", line 137, in __getitem__
    o = self.data[key]()
KeyError: 'cinnamon-translations'